# my global config
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: tofs
    scrape_interval: 5s
    basic_auth:
          username: 'onprem'
          password: 'onprem'
    metrics_path: /prometheus
    static_configs:
        - targets:
          - localhost:8080