server:
  port: 8080

logging:
  file: /Users/himansunayak/TOFS/innovation/springbootadmin/logs/log.log
  level:
    com.jci.tofs.sba: DEBUG

spring:
  application:
    name: a-bootiful-client
  profiles:
    active: secure
  boot:
    admin:
      url: http://localhost:8000/
      auto-registration: true
      client:
        metadata:
          user:
            name: onprem
            password: onprem

#endpoints:
#  prometheus:
#    path: prometheus-metrics
#endpoints:
#  jolokia:
#    sensitive: false

# eureka setup
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8182/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

---
spring:
  profiles: insecure

management:
  security:
    enabled: false

security:
  basic:
    enabled: false
---
spring:
  profiles: secure
  boot:
    admin:
      username: sbaadmin  #These two are needed so that the client
      password: sbaadmin  #can register at the protected server api
      client:
        metadata:
          user.name: "${security.user.name}"          #These two are needed so that the server
          user.password:  "${security.user.password}" #can access the protected client endpoints

security:
  user:
    name: onprem
    password: onprem
