server:
  port: 8080

logging:
  file: /Users/himansunayak/TOFS/innovation/github/sba/sba-client/logs/log.log
  level:
    com.jci.tofs.sba: DEBUG

spring:
  application:
    name: a-bootiful-client
  profiles:
    active: secure
  boot:
    admin:
      url: http://localhost:8000/
      auto-registration: true
      client:
        metadata:
          user:
            name: onprem
            password: onprem
endpoints:
  jolokia:
    sensitive: false

#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#    metadataMap:
#      instanceId: ${spring.application.name}:${spring.application.instance_id}
#      management:
#        contextPath: ${server.context-path}
#    statusPageUrlPath: ${server.context-path}/info
#    healthCheckUrlPath: ${server.context-path}/health
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8180/eureka/
#    healthcheck:
#      enabled: true
#    lease:
#      duration: 5


---
spring:
  profiles: insecure

management:
  security:
    enabled: false

security:
  basic:
    enabled: false
---
spring:
  profiles: secure
  boot:
    admin:
      username: sbaadmin  #These two are needed so that the client
      password: sbaadmin  #can register at the protected server api
      client:
        metadata:
          user.name: "${security.user.name}"          #These two are needed so that the server
          user.password:  "${security.user.password}" #can access the protected client endpoints

security:
  user:
    name: onprem
    password: onprem
