spring:
  application:
    name: sba-eureka
#  boot:
#    admin:
#      url: http://localhost:8000/
#      username: sbaadmin
#      password: sbaadmin

server:
  port: 8182

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
        defaultZone: http://127.0.0.1:8182/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  security:
    enabled: false